all:
  hosts:
    hetzner_vm:
      ansible_host: "{{ public_ip }}"
      ansible_user: "{{ sudo_user }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_PRIVATE_KEY_FILE') }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"