name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
      env:
        GITHUB_SECRET_VAR1: ${{ secrets.VAR1 }}
        GITHUB_SECRET_VAR2: ${{ secrets.VAR2 }}
