name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Deploy using Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          app_name: pasha-bot
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          tg_token: ${{ secrets.TG_TOKEN }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          ansible_user: ${{ secrets.USERNAME }}
        run: |
          ansible-playbook -i ${{ secrets.SERVER_IP }}, playbook.yml --extra-vars "ansible_user=${{ secrets.USERNAME }}"

