name: Build and Push Docker Image to GitHub Container Registry

# Trigger the workflow on push to main or any changes in the app directory
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Log in to the GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Set up Python environment and install dependencies (optional for building)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/pasha-bot:latest .

    # Push the Docker image to GitHub Container Registry
    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}/pasha-bot:latest
